name: Deploy Shared Hub

on:
  push:
    branches:
      - main
    paths:
      - "network/**"
      - "modules/hub_network/**"
      - "modules/tags/**"
      - ".github/workflows/deploy-hub.yml"
      - ".github/workflows/reusable-terraform.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: hub
      working_directory: network
      backend_key: network.tfstate
      apply: true